### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by vitich** [mxmCherry/taxes#1]
When I first start the program, I get an error. Then for some time it works fine. Further the situation is repeated.

`Get https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?valcode=USD&date=20190705&json: read tcp xxx.xxx.xxx.xxx:59870->193.17.44.146:443: read: connection reset by peer
`

**Comment by mxmCherry** [comment]
This is definitely a problem either with:

- bank.gov.ua itself
- or any proxies on the way to it
- or your internet connection

It's not really solvable via code, I can suggest only waiting and retrying. And storing result - it's not going to change across runs, unless source data (yaml) changes.

Introducing some cache (at least for currencies) or retries in code can probably improve it, but I have no plans to improve current version - aiming for almost complete rewrite using better-precision decimal implementation, but this is not going to happen soon (1-2 months, probs even later).

**Comment by vitich** [comment]
Previously, I used my own shell script and also used the api of the national bank - there are no such problems. The behavior is the same both through the proxy and from the server in the DC. In any case, this is a minor bug, and the program works correctly.
Thank you.
