### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by vitich** [mxmCherry/taxes#2]
```
$ taxes 
invalid character '<' looking for beginning of value

```

**Comment by mxmCherry** [comment]
Most likely some tmp error when pulling currency - maybe some mistake in currency code?
Also, you can try to reduce number of transactions kept in the file - I comment out everything that's not from current year (or two) - maybe there are too many requests?

I agree that err messages could be clearer, but don't want to waste too much time on that if re-run fixes the issue. This tool is not supposed to run perfectly all the time (esp given it depends on third-party services), I wanted it to "just work" and do correct calcs.

**Comment by vitich** [comment]
Everything works great! 
I completely forgot about the temporary errors on the NBU site. 
Thanks a lot!
