### ISSUE TITLE
Wrong rounding

### ISSUE THREAD

**Issue by vitich** [mxmCherry/taxes#3]
Did not calculate the third quarter correctly - through privat24 and through Diya 5% tax amount is 5000.10 but in your program 5000.11 - 1 kopeck more... bank rounding again?

**Comment by mxmCherry** [comment]
Yes, looks that this tool is more precise than needed, already faced this.

IIRC I'm just opting for less precise bank rounding when submitting tax declaration, don't think 0.01 really matters.

**Comment by vitich** [comment]
Yes, 1 kopeck does not really matter, but I have been using your program for several years as a ledger and almost all this time the tax was calculated correctly. It would be cool to be able to change the rounding rule using the option. Anyway, thanks for the program and for the feedback!

**Comment by vitich** [comment]
Hi! And again for the fourth quarter, one kopeck more than necessary :( 
Is there a way to fix it? I would pay.

**Comment by mxmCherry** [comment]
The only way you can "pay" is by PRing the fix yourself :)

But I've started [v2](https://github.com/mxmCherry/taxes/tree/v2) a few months ago, and I think I'll have some time till the end of the year to add rounding (I kept this issue open to address it in v2).

For now, I suggest you to correct this extra kopeck manually and not dig into fixing v1 as v2 is on its way.

**Comment by mxmCherry** [comment]
Addressed in v2: https://github.com/mxmCherry/taxes/pull/4

I expect to merge it within this week, but you should already be able to experiment with it by `go install github.com/mxmCherry/taxes@v2` and optionally migrating your data with:

```shell
go install github.com/mxmCherry/taxes/cmd/taxes_migrate@v2
cat ~/.taxes/data.yaml | taxes_migrate > taxes.yaml
```

See README changes: https://github.com/mxmCherry/taxes/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I'm closing this issue now.

**Comment by vitich** [comment]
$ go install github.com/mxmCherry/taxes@v2
go install github.com/mxmCherry/taxes@v2: no matching versions for query "v2"

**Comment by mxmCherry** [comment]
Tagged it just now.

See latest [README](https://github.com/mxmCherry/taxes#readme) (incl. migrating from prev version).

Don't forget to add the `rounding_precision: 2` to converted v2 data file to apply rounding. But keep the old (v1) data file! Just in case anything's wrong.

Double-check results after migration (with 2021's data), give some feedback, open issues if you encounter any bugs. I did automated tests for v2 (see internal/tax + internal/tax/testdata), but everyone can make mistakes.

To revert back to v1, run `go install github.com/mxmCherry/taxes@v1.0.0`. 

I suggest to use v1 to declare income/taxes for 2021, do kopeck-rounding manually.

Better use v2 only for 2022's data - just start collecting your transactions in v2 format in another file and double-check first report (in April 2022).

**Comment by mxmCherry** [comment]
Just in case, to revert back to old version v1 (keep old data file!) do: `go install github.com/mxmCherry/taxes@v1.0.0`.
